// Copyright Kyle Cuss and Cuss Programming 2026

#pragma once

#include "CoreMinimal.h"

#include "NativeGameplayTags.h"

/** Central declarations for the native gameplay tags used by the ability system. */
namespace CussAbilityTags
{
	// --------------------
	// Abilities
	// --------------------
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Fireball);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Heal);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Burn);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Rally);
	
	// --------------------
	// Statuses
	// --------------------
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Dead);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Stunned);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Silenced);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Buffed);
	
	// --------------------
	// Stats
	// --------------------
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stat_Health);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stat_Mana);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stat_Energy);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stat_AttackPower);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Stat_Defense);
	
	// --------------------
	// Cues
	// --------------------
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cue_Cast_Fire);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cue_Impact_Fire);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cue_Cast_Heal);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cue_Impact_Heal);

	// --------------------
	// Cooldowns
	// --------------------
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Cooldown_Magic_Basic);
	
	// --------------------
	// Inputs
	// --------------------
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_Primary);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_Secondary);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_Utility);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Ability_Ultimate);
	
	// --------------------
	// Teams
	// --------------------
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Team_Player);
	CUSSABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Team_Enemy);
}
